### ISSUE TITLE
Beginnner Questions

### ISSUE THREAD

**Issue by CrazyWolf13** [jakob-bagterp/browserist#518]
Hi you just recommended me your software on stackoverflow:
https://stackoverflow.com/questions/78043266/python-subprocess-launch-new-chrome-tab/78043976#78043976

Now I have some questions to this software, sadly could't find an answer on the wiki.

- How to get my chrome profile to open instead of Profile 1
- How to get rid of this message: 
![image](https://github.com/jakob-bagterp/browserist/assets/96661824/f9c08e04-4ba5-4658-ae9f-88e5cb370fac)
- How to keep the browser alive after python script finishes
- How to open browser in fullscreen 

Thanks for any help!

**Comment by jakob-bagterp** [comment]
I hope the following is helpful.

> * How to get my chrome profile to open instead of Profile 1

You can't with Chromedriver as it runs a special instance of your Chrome browser. It's a specialised tool for automation orchestrated with Selenium and then Browserist as extension.

> * How to get rid of this message:
>   ![image](https://private-user-images.githubusercontent.com/96661824/307414258-f9c08e04-4ba5-4658-ae9f-88e5cb370fac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTM1MTQsIm5iZiI6MTcwODcxMzIxNCwicGF0aCI6Ii85NjY2MTgyNC8zMDc0MTQyNTgtZjljMDhlMDQtNGJhNS00NjU4LWFlOWYtODhlNWNiMzcwZmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE4MzMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMWIzMjY2NjBjZjcxZTNjYjdkNjYzMDVlY2M0ZTBmODY1YWYxY2Y5NGI1MWNiYzhlMDM5NmFhZDY4NGE2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o51-W4JxjtSXB_c07844DAku8NJLuROcTSKaONGYzwU)

As above, Chromedriver is a special instance of your Chrome browser so you can't. Not sure why this is important to get your job done. If you care about aesthetics, Chromedriver is probably not the right tool for you. 

> * How to keep the browser alive after python script finishes

That's why I added a loop at the end of your script so you close Chromedriver where you started it, i.e. from the terminal.

> * How to open browser in fullscreen

Please refer the [documentation of how to toggle fullscreen mode on](https://jakob-bagterp.github.io/browserist/reference/browser/window/__main__/#browserist.browser.window.__main__.WindowDriverMethods.fullscreen).

```python
browser.window.fullscreen()
```

**Comment by CrazyWolf13** [comment]
Then sadly browserist was not the kind of tool I search for. I need an automated launcher, that launches all tabs for me on pc sartup not an automated testing tool.

Anyway thanks!
